### PR TITLE
Emqtt

### PR DESCRIPTION
**Pull request by ejvr**
Fix for issue #238

### CODE REVIEW

**Review by mwallnoefer — CHANGES_REQUESTED** [review]
I would prefer using `nullptr` instead since `NULL` is more thought to be for C-code backwards compatibility: https://en.cppreference.com/w/cpp/language/nullptr

**Comment by ejvr** [comment]
Yeah, normally I'd use `nullptr` as well. However, as far as I know, that `qmqtt` is written in the C++-98 standard, which does not define `nullptr`. That was my reason for choosing `NULL`.

Please let me know what you think of my decision. If you don't like it, I'd be happy convert the NULLs to nullptrs.

**Comment by ejvr** [comment]
Good point, I'll make the necessary changes.

**Comment by ejvr** [comment]
Closing this PR, because I made a mess of it. Will create a new one

**Comment by ejvr** [comment]
Accidentally close the PR. It should be good now...

**Pull request merged**
