### PR TITLE
Changes to be able to compile the library with Qt 6.2.0.

### PR DESCRIPTION
**Pull request by alex-spataru**
Trying to compile the library with Qt 6 results with the following error:

Screen Shot 2021-09-28 at 14 51 08

The fix that I came up with was simply changing the `QString` in the `Q_PROPERTY` to an `int` or a `ConnectionState` type.

### CODE REVIEW

**Comment by alex-spataru** [comment]
Please let me know if I should close this PR, for the moment I am using my fork for Qt 6 applications.

**Review by JaylinYu — APPROVED** [review]

**Comment by mwallnoefer** [comment]
@ejvr is this fine to merge in?

**Comment by ejvr** [comment]
Yep, I see no problems

**Comment by mwallnoefer** [comment]
Unfortunately I had to revert this, it breaks the build on Qt5 (also when disabling the new definition `MQTT_INCLUDE_MOC`). Very strange...

See PR #237.

**Pull request merged**
